name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: v2.11.4

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
      - name: Build
        run: make build
      - name: Test
        run: make test
  #  tag-major:
  #    name: tag major
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: kobtea/release-tag-action@master
  #        with:
  #          force: true
  #          only_major_version: true
  # tag-full:
  #   name: tag full
  #   needs:
  #     - lint
  #     - build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.PERSONAL_TOKEN }}
  #     - uses: kobtea/release-tag-action@master
  #       with:
  #         message: gogo __VERSION__
  #         version_file: ./sub/VERSION
