name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CGO_ENABLED: 0

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
        with:
          version: v2.13.2

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6
      - name: Build
        run: make build
      - name: Test
        run: make test
  #  tag-major:
  #    name: tag major
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: kobtea/release-tag-action@master
  #        with:
  #          force: true
  #          only_major_version: true
  # tag-full:
  #   name: tag full
  #   needs:
  #     - lint
  #     - build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         token: ${{ secrets.PERSONAL_TOKEN }}
  #     - uses: kobtea/release-tag-action@master
  #       with:
  #         message: gogo __VERSION__
  #         version_file: ./sub/VERSION
